# ─────────────────────────────────────────────────────────
#  Mosquitto – Configuración para CerradurasIoT Empresa v3.1
# ─────────────────────────────────────────────────────────

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

# ── Puerto MQTT nativo (daemon Python / Home Assistant) ──
listener 1883
protocol mqtt

# ── Puerto WebSockets (navegador) ────────────────────────
listener 9001
protocol websockets

allow_anonymous true

max_queued_messages 1000
